### ISSUE TITLE
Suggestion: Add not only O(n) for the worst case but also average for passwords of fewer characters

### ISSUE THREAD

**Issue by Ordiel** [gusleyva/c4cydonia-brute-force#1]
Big O on the README is for the worst-case scenario, maybe get an average for the O(n) after performing multiple runs on different passwords of different length; take the passwords randomly from a dictionary else it would be deterministic, i.e: if your dictionary is only composed from the letters of the (English) alphabet and you limit it to 1 char A would have O(n) = 1 and Z would be O(n) = 26

**Comment by gusleyva** [comment]
Hey Ordiel!
I appreciate the time to review the general details and feedback.
A couple of comments:
1. Agree, having a dictionary could have different paths, should be Spanish, English, LA? Well I will consider that information to create/use a dictionary, what about profiling in order to reduce time? How much I know about the possible password, hobbies, pets, dates, etc.
2. After experimenting with brute force, the problem with having an average time will be the length, if we follow accepted rule for 8 chars, combine digits, letters and symbols, well, that will be fun, said that, if someone starts adding more chars (9, 10...), declaring that we could have an average time it will be (from my perspective) inaccurate.
3. Personally, I will prefer to have in mind that could take 3 weeks and solve it in 2 days that have an average time of 1 week and code has been running for 2 weeks without a success answer; In the last scenario, I will start wondering, is there something wrong with the code? Should I stop it?
4. A different approach to clone the file and multithreading it will be something to consider and evaluate.

**Comment by gusleyva** [comment]
> Hey Ordiel! I appreciate the time to review the general details and feedback. A couple of comments:
> 
> 1. Agree, having a dictionary could have different paths, should be Spanish, English, LA? Well I will consider that information to create/use a dictionary, what about profiling in order to reduce time? How much I know about the possible password, hobbies, pets, dates, etc.
> 2. After experimenting with brute force, the problem with having an average time will be the length, if we follow accepted rule for 8 chars, combine digits, letters and symbols, well, that will be fun, said that, if someone starts adding more chars (9, 10...), declaring that we could have an average time it will be (from my perspective) inaccurate.
> 3. Personally, I will prefer to have in mind that could take 3 weeks and solve it in 2 days that have an average time of 1 week and code has been running for 2 weeks without a success answer; In the last scenario, I will start wondering, is there something wrong with the code? Should I stop it?
> 4. A different approach to clone the file and multithreading it will be something to consider and evaluate.
